# Generated by Django 3.1.1 on 2020-11-06 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeApp', '0003_category_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
